### ISSUE TITLE
Mediapartners\-Google should be added to Robots list.

### ISSUE THREAD

**Issue by rubakharrubi** [atmire/COUNTER-Robots#12]
user-agent is a case insensitive substring match.

so as per:  https://support.google.com/adsense/answer/99376?hl=en&visit_id=1-636565585661074629-419118318&rd=1
Mediapartners\-Google should be added instead of mediapartners\-google

**Comment by tomdesair** [comment]
Hi @rubakharrubi,

Thanks for your suggestion! The COUNTER list already contains the regex ["google"](https://github.com/atmire/COUNTER-Robots/blob/2018-02-16/generated/COUNTER_Robots_list.txt#L104). Since matching should be done case-insensitive and a regex only needs to match a part of the user agent, I think we already cover the "Mediapartners-Google" user agent.

What do you think?

Best regards,
Tom

**Comment by rubakharrubi** [comment]
Hi Tom,

Thank you for your reply!
So you are matching case-insensitive. I thought the matching is case-sensitive this is why I thought that this crawler is not covered then.

Best regards,
Ruba

**Comment by bram-atmire** [comment]
Added a recommendation about implementing/using the pattern list with case insensitive matching in the README.md to close this out.
