### ISSUE TITLE
Firefox and Opera browsers excluded?

### ISSUE THREAD

**Issue by jrfreez** [atmire/COUNTER-Robots#59]
I think these patterns will exclude anyone using the Firefox or Opera browsers from being counted:
^Mozilla$
^Mozilla.4\.0$
^Mozilla\/4\.0\+\(compatible;\)$
^Mozilla\/4\.0\+\(compatible;\+ICS\)$
^Mozilla\/4\.5\+\[en]\+\(Win98;\+I\)$
^Mozilla.5\.0$
^Mozilla\/5.0\+\(compatible;\+MSIE\+6\.0;\+Windows\+NT\+5\.0\)$
^Mozilla\/5\.0\+like\+Gecko$
^Mozilla\/5.0(\s|\+)Gecko\/20100115(\s|\+)Firefox\/3.6$
^Opera\/4$

**Comment by alanorth** [comment]
Hi @jrfreeze. The patterns you mentioned are very specifically targeting user agents that _look_ like they are valid. Due to the fact that the patterns are anchored at the beginning (`^`) and the end (`$`) of the string, they will never match a real browser user agent.

For example, my current user agent is this:

```console
Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
```

You can test some of the regular expressions above against my user agent using [regex101.com](https://regex101.com/r/6LjoS8/1).

_Note: these patterns have been in the set for years and they could actually be improved. At the very least, they are not escaping some literal characters `/` and `+` correctly._

**Comment by jrfreez** [comment]
Oops. I somehow overlooked the end anchors. Sorry about that.
